apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  annotations:
    crossplane.io/composition-resource-name: igw
    crossplane.io/external-create-pending: "2025-10-30T09:57:27Z"
    crossplane.io/external-create-succeeded: "2025-10-30T09:57:27Z"
    crossplane.io/external-name: igw-0e2070349d0301923
  creationTimestamp: "2025-10-30T09:53:26Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 3
  labels:
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
    protection.fn.crossplane.io/block-deletion: "true"
  name: configuration-aws-network-ff951409171d
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XNetwork
    name: configuration-aws-network
    uid: 7d347895-8e7e-417f-bfdf-6eb149ab2fd6
  resourceVersion: "5255"
  uid: 82c551dc-2bd6-44e8-9699-f6d851d106c2
spec:
  deletionPolicy: Delete
  forProvider:
    region: us-west-2
    tags:
      crossplane-kind: internetgateway.ec2.aws.upbound.io
      crossplane-name: configuration-aws-network-ff951409171d
      crossplane-providerconfig: default
    vpcId: vpc-008cddc3dfb1acdb6
    vpcIdRef:
      name: configuration-aws-network-c82ef4fa3e45
    vpcIdSelector:
      matchControllerRef: true
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    arn: arn:aws:ec2:us-west-2:609897127049:internet-gateway/igw-0e2070349d0301923
    id: igw-0e2070349d0301923
    ownerId: "609897127049"
    tags:
      crossplane-kind: internetgateway.ec2.aws.upbound.io
      crossplane-name: configuration-aws-network-ff951409171d
      crossplane-providerconfig: default
    tagsAll:
      crossplane-kind: internetgateway.ec2.aws.upbound.io
      crossplane-name: configuration-aws-network-ff951409171d
      crossplane-providerconfig: default
    vpcId: vpc-008cddc3dfb1acdb6
  conditions:
  - lastTransitionTime: "2025-10-30T09:57:27Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2025-10-30T09:57:33Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-10-30T09:57:30Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
