apiVersion: ec2.aws.upbound.io/v1beta1
kind: MainRouteTableAssociation
metadata:
  annotations:
    crossplane.io/composition-resource-name: mrt
    crossplane.io/external-create-pending: "2025-10-30T09:58:29Z"
    crossplane.io/external-create-succeeded: "2025-10-30T09:58:29Z"
    crossplane.io/external-name: rtbassoc-03d9cf0c612cf0289
  creationTimestamp: "2025-10-30T09:53:26Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 3
  labels:
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
  name: configuration-aws-network-1bee295a7f12
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XNetwork
    name: configuration-aws-network
    uid: 7d347895-8e7e-417f-bfdf-6eb149ab2fd6
  resourceVersion: "5764"
  uid: 6e85b634-e24e-4944-9b5c-ca0debcb91ba
spec:
  deletionPolicy: Delete
  forProvider:
    region: us-west-2
    routeTableId: rtb-07a91a1ea2dc67d19
    routeTableIdRef:
      name: configuration-aws-network-7d8b3d27ab21
    routeTableIdSelector:
      matchControllerRef: true
    vpcId: vpc-008cddc3dfb1acdb6
    vpcIdRef:
      name: configuration-aws-network-c82ef4fa3e45
    vpcIdSelector:
      matchControllerRef: true
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    id: rtbassoc-03d9cf0c612cf0289
    originalRouteTableId: rtb-0410d4125e467e466
    routeTableId: rtb-07a91a1ea2dc67d19
    vpcId: vpc-008cddc3dfb1acdb6
  conditions:
  - lastTransitionTime: "2025-10-30T09:58:29Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2025-10-30T09:59:32Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-10-30T09:58:31Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
