apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  annotations:
    crossplane.io/composition-resource-name: rt
    crossplane.io/external-create-pending: "2025-10-30T09:57:27Z"
    crossplane.io/external-create-succeeded: "2025-10-30T09:57:27Z"
    crossplane.io/external-name: rtb-07a91a1ea2dc67d19
  creationTimestamp: "2025-10-30T09:53:26Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 3
  labels:
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
  name: configuration-aws-network-7d8b3d27ab21
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XNetwork
    name: configuration-aws-network
    uid: 7d347895-8e7e-417f-bfdf-6eb149ab2fd6
  resourceVersion: "7530"
  uid: a3f107a8-8546-40c9-a981-496cdcb335ac
spec:
  deletionPolicy: Delete
  forProvider:
    region: us-west-2
    tags:
      crossplane-kind: routetable.ec2.aws.upbound.io
      crossplane-name: configuration-aws-network-7d8b3d27ab21
      crossplane-providerconfig: default
    vpcId: vpc-008cddc3dfb1acdb6
    vpcIdRef:
      name: configuration-aws-network-c82ef4fa3e45
    vpcIdSelector:
      matchControllerRef: true
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    arn: arn:aws:ec2:us-west-2:609897127049:route-table/rtb-07a91a1ea2dc67d19
    id: rtb-07a91a1ea2dc67d19
    ownerId: "609897127049"
    route:
    - carrierGatewayId: ""
      cidrBlock: 0.0.0.0/0
      coreNetworkArn: ""
      destinationPrefixListId: ""
      egressOnlyGatewayId: ""
      gatewayId: igw-0e2070349d0301923
      ipv6CidrBlock: ""
      localGatewayId: ""
      natGatewayId: ""
      networkInterfaceId: ""
      transitGatewayId: ""
      vpcEndpointId: ""
      vpcPeeringConnectionId: ""
    tags:
      crossplane-kind: routetable.ec2.aws.upbound.io
      crossplane-name: configuration-aws-network-7d8b3d27ab21
      crossplane-providerconfig: default
    tagsAll:
      crossplane-kind: routetable.ec2.aws.upbound.io
      crossplane-name: configuration-aws-network-7d8b3d27ab21
      crossplane-providerconfig: default
    vpcId: vpc-008cddc3dfb1acdb6
  conditions:
  - lastTransitionTime: "2025-10-30T09:57:27Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2025-10-30T09:58:30Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-10-30T09:57:30Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
