apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  annotations:
    crossplane.io/composition-resource-name: rta-us-west-2a-public
    crossplane.io/external-create-pending: "2025-10-30T09:58:29Z"
    crossplane.io/external-create-succeeded: "2025-10-30T09:58:29Z"
    crossplane.io/external-name: rtbassoc-0b97b842145ce0757
  creationTimestamp: "2025-10-30T09:53:26Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 3
  labels:
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
  name: configuration-aws-network-95b0b7410d10
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XNetwork
    name: configuration-aws-network
    uid: 7d347895-8e7e-417f-bfdf-6eb149ab2fd6
  resourceVersion: "5765"
  uid: e063851a-09d7-4444-b90b-c4df1a010812
spec:
  deletionPolicy: Delete
  forProvider:
    region: us-west-2
    routeTableId: rtb-07a91a1ea2dc67d19
    routeTableIdRef:
      name: configuration-aws-network-7d8b3d27ab21
    routeTableIdSelector:
      matchControllerRef: true
    subnetId: subnet-0c469242854340043
    subnetIdRef:
      name: configuration-aws-network-c81f5c3baf23
    subnetIdSelector:
      matchControllerRef: true
      matchLabels:
        access: public
        zone: us-west-2a
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    gatewayId: ""
    id: rtbassoc-0b97b842145ce0757
    routeTableId: rtb-07a91a1ea2dc67d19
    subnetId: subnet-0c469242854340043
  conditions:
  - lastTransitionTime: "2025-10-30T09:58:29Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2025-10-30T09:59:32Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-10-30T09:58:31Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
